### ISSUE TITLE
What is the default shortcut / hotkey / accelerator?

### ISSUE THREAD

**Issue by ElectricPrism** [tetzank/qmenu_hud#1]
What is the default shortcut / hotkey / accelerator? Does it even have one? If not it should. That would help a lot.

**Comment by fogine** [comment]
I don't think it has default shortcut.
You can however bind the shortcut yourself, I suppose you know that.
The library provide only the binary files. There is no installation process whatsoever so no reason for automatic polluting of system wide settings I think...

Example settings for `i3-wm`:  

``` bash
exec qmenu_registrar
bindsym $mod+x exec qmenu_hud
```

`qmenu_registrar` and `qmenu_hud` binary files should be in you `PATH`.

**Comment by tetzank** [comment]
As described by fogine, there's no default shortcut. I'm not even aware of any default way to define shortcuts which is respected by all DEs/WMs. You have to define your own.
