### ISSUE TITLE
Installation problems II

### ISSUE THREAD

**Issue by lw3eov** [tetzank/qmenu_hud#12]
On step 4 for Debian distros (ubuntu, etc) of: https://github.com/shinnok/johnny/blob/master/INSTALL

$ qmake && make -j$(nproc)
qmake: could not exec '/usr/lib/qt5/bin/qmake': No such file or directory
m@m-desktop:~$ sudo apt-get install qmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qmake

Doing some search I've found this: https://github.com/tetzank/qmenu_hud/issues/4
But none of those suggestions worked

**Comment by tetzank** [comment]
I'm closing this issue as I am not able to give support for an unrelated project. You should ask the developers of the project you are trying to build, or ask for help in the support forums of your distribution.
